"""empty message

Revision ID: 7b4f0d6ad891
Revises: c9f082ee1b0d
Create Date: 2020-07-27 18:36:26.856470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4f0d6ad891'
down_revision = 'c9f082ee1b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_price', sa.Integer(), nullable=False),
    sa.Column('item_rating', sa.Integer(), nullable=False),
    sa.Column('item_img', sa.Integer(), nullable=False),
    sa.Column('test', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_name', sa.String(), nullable=False),
    sa.Column('restaurant_description', sa.String(), nullable=False),
    sa.Column('restaurant_rating', sa.Integer(), nullable=True),
    sa.Column('restaurant_location', sa.String(), nullable=True),
    sa.Column('restaurant_hours_of_operation', sa.String(), nullable=True),
    sa.Column('restaurant_img_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_title', sa.String(), nullable=True),
    sa.Column('review_description', sa.String(), nullable=True),
    sa.Column('review_score', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('restaurants')
    op.drop_table('menu_item')
    # ### end Alembic commands ###
