"""empty message

Revision ID: b4e1bf25b292
Revises: acd577371f5e
Create Date: 2020-08-11 08:17:13.623030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b4e1bf25b292"
down_revision = "acd577371f5e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("restuarant_reviews")
    op.add_column("reviews", sa.Column("restaurant_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "reviews", "restaurants", ["restaurant_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.drop_column("reviews", "restaurant_id")
    op.create_table(
        "restuarant_reviews",
        sa.Column("restaurant_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("review_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name="restuarant_reviews_restaurant_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["review_id"], ["reviews.id"], name="restuarant_reviews_review_id_fkey"
        ),
        sa.PrimaryKeyConstraint(
            "restaurant_id", "review_id", name="restuarant_reviews_pkey"
        ),
    )
    # ### end Alembic commands ###
